name: Build and Publish Docker Image

on:
  push:
    tags:
      - '*'   # Run when a new tag is pushed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed for pushing to GitHub Container Registry

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract Repository and Image Name
        id: vars
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository }}"  
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')  # Ensure lowercase
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Get Version Tag (if applicable)
        id: version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="latest"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

          # Also push "latest" if this build is from main
          if [[ "$TAG" != "latest" ]]; then
            docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
          fi